app:
  mysql:
    enabled: true
    url: root:root@(47.106.183.226:3306)/go-mirco?charset=utf8&parseTime=true&loc=Asia%2FShanghai
    maxIdleConnection: 100
    maxOpenConnection: 130
    connMaxLifetime: 100